[package]
name = "wsus-fuzz"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[workspace]

[dependencies]
honggfuzz = "0.5"
wsus-protocol = { version = "0.1.0", path = "../crates/wsus-protocol" }

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[profile.release]
debug = 1
overflow-checks = true
